### ISSUE TITLE
Error Cannot find module 'localforage' 

### ISSUE THREAD

**Issue by frederic117** [elonehoo/nuxt-localforage#9]
Hello I try your module with "nuxt": "^3.8.2", but i got an error : 
Require stack:
  - node_modules\nuxt3-localforage\dist\module.mjs
  at Module._resolveFilename (node:internal/modules/cjs/loader:1077:15)
 ERROR  Cannot find module 'localforage'

**Comment by elonehoo** [comment]
ah ha, let me try to fix it

**Comment by elonehoo** [comment]
try 0.1.2, there is no problem in my playground
